// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6EXRnCIPQnBiVoCl73UDI-VBoGDwjE4',
    appId: '1:407635039395:web:7e4ebbfbb07b38ab9adb16',
    messagingSenderId: '407635039395',
    projectId: 'quizzgame-d61d6',
    authDomain: 'quizzgame-d61d6.firebaseapp.com',
    storageBucket: 'quizzgame-d61d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshNUoBnG7Jh_IPwPoRJLF27k_j7qrWcc',
    appId: '1:407635039395:android:39f78124caef3ee19adb16',
    messagingSenderId: '407635039395',
    projectId: 'quizzgame-d61d6',
    storageBucket: 'quizzgame-d61d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDni1sk2towzZlCKMce3q1Am3KWTqrzWdM',
    appId: '1:407635039395:ios:accebd608946c7249adb16',
    messagingSenderId: '407635039395',
    projectId: 'quizzgame-d61d6',
    storageBucket: 'quizzgame-d61d6.firebasestorage.app',
    iosBundleId: 'com.example.quizzGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDni1sk2towzZlCKMce3q1Am3KWTqrzWdM',
    appId: '1:407635039395:ios:accebd608946c7249adb16',
    messagingSenderId: '407635039395',
    projectId: 'quizzgame-d61d6',
    storageBucket: 'quizzgame-d61d6.firebasestorage.app',
    iosBundleId: 'com.example.quizzGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd6EXRnCIPQnBiVoCl73UDI-VBoGDwjE4',
    appId: '1:407635039395:web:ed52ebb233c874e29adb16',
    messagingSenderId: '407635039395',
    projectId: 'quizzgame-d61d6',
    authDomain: 'quizzgame-d61d6.firebaseapp.com',
    storageBucket: 'quizzgame-d61d6.firebasestorage.app',
  );
}
